server:
  port: 8080

# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lpc.studydemo.entity

# 配置spring
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql_study?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  # 配置freemarker
  freemarker:
    cache: false # 是否缓存
    suffix: .ftl # 模板文件后缀
    settings:
      template_update_delay: 0 # 模板更新延迟时间
    template-loader-path: classpath:/templates # 模板文件路径
